### ISSUE TITLE
memery leak

### ISSUE THREAD

**Issue by sgsungeng** [SnapKit/SnapKit#440] opened 2017-08-26 09:16 UTC
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

I use this kit find some memery leak

**Comment by robertjpayne** [comment] 2017-08-26 10:41
Dupe of #310 it's not a memory leak but rather instruments is profiling wrong.

**Closed by robertjpayne** 2017-08-26 10:41 UTC
