### ISSUE TITLE
Carthage build fail with version 3.1.0

### ISSUE THREAD

**Issue by Zeotyn** [SnapKit/SnapKit#349] opened 2016-10-07 13:20 UTC
* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.0
 SnapKit Version         | 3.1.0
 Integration Method      | carthage
 

### Issue Description

Hi there,

I have an issue while carthage builds SnapKit 3.1.0. The error looks like this:

` The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Playground/Carthage/Checkouts/SnapKit/Source/LayoutConstraintItem.swift:55:20: error: value of type 'ConstraintLayoutGuide' has no member 'owningView'
A shell task (/usr/bin/xcrun xcodebuild -workspace /Playground/Carthage/Checkouts/SnapKit/SnapKit.xcworkspace -scheme SnapKit -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures) `

The earlier version(3.0.2) works fine. 

Thanks

**Comment by PravdaEvgen** [comment] 2016-10-07 15:29
Have the same Issue

**Comment by robertjpayne** [comment] 2016-10-08 03:03
Dupe of #348

**Closed by robertjpayne** 2016-10-08 03:03 UTC
