### ISSUE TITLE
LayoutConstraintItem.swift:55:20: error: value of type 'ConstraintLayoutGuide' has no member 'owningView'

### ISSUE THREAD

**Issue by sadiq81** [SnapKit/SnapKit#352] opened 2016-10-10 05:58 UTC
Platform                | e.g. iOS
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 3.1.0
 Integration Method      carthage
 
### Issue Description

When building with "carthage update" i get the following error message

```
*** Building scheme "SnapKit" in SnapKit.xcworkspace
** BUILD FAILED **


The following build commands failed:
        CompileSwift normal x86_64
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:78:28: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:71:29: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/iOS/UITableView+Rx.swift:388:35: warning: 'observe' is deprecated: renamed to 'methodInvoked'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/iOS/UICollectionView+Rx.swift:303:31: warning: 'observe' is deprecated: renamed to 'methodInvoked'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:78:28: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:71:29: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/iOS/UITableView+Rx.swift:388:35: warning: 'observe' is deprecated: renamed to 'methodInvoked'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/iOS/UICollectionView+Rx.swift:303:31: warning: 'observe' is deprecated: renamed to 'methodInvoked'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:78:28: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:71:29: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:78:28: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:71:29: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:78:28: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:71:29: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:78:28: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/RxSwift/RxCocoa/Common/TextInput.swift:71:29: warning: 'RxTextInput' is deprecated: renamed to 'TextInput'
/Users/Privat/Documents/punchcards/Carthage/Checkouts/SnapKit/Source/LayoutConstraintItem.swift:55:20: error: value of type 'ConstraintLayoutGuide' has no member 'owningView'
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/Privat/Documents/punchcards/Carthage/Checkouts/SnapKit/SnapKit.xcworkspace -scheme SnapKit -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
        CompileSwift normal x86_64
        CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by robertjpayne** [comment] 2016-10-10 05:58
Dupe of #348

**Closed by robertjpayne** 2016-10-10 05:58 UTC
