### ISSUE TITLE
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/Demo/Pods/SnapKit/Source/Constraint.swift:141:15: Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true

### ISSUE THREAD

**Issue by confile** [SnapKit/SnapKit#149] opened 2015-09-21 10:54 UTC
Swift 2.0

I get the following warnings: 

``` 
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/Demo/Pods/SnapKit/Source/Constraint.swift:141:15: Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true
```

```
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/Demo/Pods/SnapKit/Source/Constraint.swift:152:15: Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true
```

```
/Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/Demo/Pods/SnapKit/Source/ConstraintAttributes.swift:139:15: Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true
```

Could you please fix that! Thanks

**Comment by robertjpayne** [comment] 2015-09-21 20:53
This is fixed in develop, pending release duplicate of #141

**Closed by robertjpayne** 2015-09-21 20:53 UTC

**Comment by confile** [comment] 2015-09-22 01:55
@robertjpayne I use the latest develop branch. I still had problems with layout guides in iOS9.

**Comment by robertjpayne** [comment] 2015-09-22 02:42
@confile ah yea, so this will be the issue with guard statements I can't find any way to get rid of the warnings as dropping the deployment target to 7.0 just causes additional warnings, it's tempting just to drop iOS 7 support as it's just causing a mess.
