### ISSUE TITLE
Error in swift 3.0

### ISSUE THREAD

**Issue by AlbertoMrFz** [SnapKit/SnapKit#321] opened 2016-09-20 09:56 UTC
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.0
 SnapKit Version         | 3.0
 Integration Method      | cocoapods
 

### Issue Description

I have this problem with swift 3.0:
![error snapkit](https://cloud.githubusercontent.com/assets/9303324/18665807/39f7a7d2-7f29-11e6-84d6-bc368ec169a6.PNG)

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

**Comment by robertjpayne** [comment] 2016-09-20 10:00
@AlbertoMrFz what version of Cocoapods are you using? Most likely I'm guessing this is related to #300 and you need to run `gem install cocoapods --pre` and ensure `pod --version` prints out `1.1.0.rc.2`

**Comment by AlbertoMrFz** [comment] 2016-09-20 10:03
Mi version of cocoapods is: 1.1.0.rc.2

**Comment by robertjpayne** [comment] 2016-09-20 10:04
@AlbertoMrFz and you've confirmed that via `pod --version` before running `pod install` and/or `pod update`?

And are you 100% sure you managed to upgrade your project to Swift 3.0 and not Swift 2.3?

**Comment by AlbertoMrFz** [comment] 2016-09-20 10:10
Yes, mi version before running pod install was: 1.1.0.rc.2

Yes i made: Edit->Convert->To current swift syntax->convert to swift 3
I convert my projects, not the pods

**Comment by robertjpayne** [comment] 2016-09-20 10:16
@AlbertoMrFz you may try deleting your `Pods/` folder and `~/Library/Developer/Xcode/DerrivedData` and also cleaning and restarting Xcode? Maybe otherwise read through #300 as I'm pretty sure it's all related.

**Comment by kimilee3232** [comment] 2016-09-21 02:54
@robertjpayne 
Hi Robert, i didn't use pod. Instead I added the source files into my project directly but I got the same issue.
I have converted my project to Swift 3.0 and turned off "User Legacy Swift Language Version" in build setting. Also, I have followed your advise, cleaned the directory "~/Library/Developer/Xcode/DerrivedData" and restarted.

**Comment by robertjpayne** [comment] 2016-09-21 02:55
@kimilee3232 you to either add it as a subproject or use cocoapods/carthage. We don't support adding the source files manually (not that it doesn't work but we don't have time to help support you integrate it this way)

Do you have a sample project? The above errors @AlbertoMrFz provided really look like a project that is set to Swift 2.3 rather than Swift 3.0.

**Comment by kimilee3232** [comment] 2016-09-21 03:15
@robertjpayne 
ok, let me turn to Pod and try again.
It is really strange that there's no such issue with a new created Swift project(still added the source files manually). Probably there's some bugs with XCode's auto conversion.

**Comment by robertjpayne** [comment] 2016-09-22 23:01
@kimilee3232 yup! That is typically the issue 👍 Cocoapods is having some weird migration issues with Swift 3.0.

@AlbertoMrFz did you have any luck? I'm going to close this as it's largely a duplicate of #300 please continue conversations over there.

**Closed by robertjpayne** 2016-09-22 23:01 UTC
