### ISSUE TITLE
Swift 3 - SnapKit 3.0.0 leaks Issues

### ISSUE THREAD

**Issue by swiftli** [SnapKit/SnapKit#310] opened 2016-09-19 01:19 UTC
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios/osx/tvos
 Platform Version        | e.g. 8.0
 SnapKit Version         | e.g. 0.19.0
 Integration Method      | e.g. carthage/cocoapods/manually
 

### Issue Description

Using Xcode 8 and Swift 3.

<img width="950" alt="2016-09-19 9 10 38" src="https://cloud.githubusercontent.com/assets/17875452/18620635/1862c7ae-7e49-11e6-920f-d311fc5b66b7.png">

demo: 
[SnapKitTest.zip](https://github.com/SnapKit/SnapKit/files/479310/SnapKitTest.zip)

**Comment by robertjpayne** [comment] 2016-09-19 03:51
@swiftli can you post more information on the leak tree? Specifically what is leaking?

It could be internal Swift stuff or SnapKit it's really hard to say. Or please attach sample project zip. Thanks!

**Comment by swiftli** [comment] 2016-09-19 05:35
Sorry, it's demo
[SnapKitTest.zip](https://github.com/SnapKit/SnapKit/files/479278/SnapKitTest.zip)

**Comment by yuyongmao** [comment] 2016-09-20 01:07
I also find many leaks that point to SnapKit

**Comment by robertjpayne** [comment] 2016-09-20 05:25
This is fixed now and published v3.0.1.

**Closed by robertjpayne** 2016-09-20 05:25 UTC
Labels: need info

**Comment by swiftli** [comment] 2016-09-20 06:28
The situation as it is before.
[SnapKitTest.zip](https://github.com/SnapKit/SnapKit/files/481751/SnapKitTest.zip)

**Comment by robertjpayne** [comment] 2016-09-20 06:35
@swiftli yea so now the issue is iOS 10 leaks memory under the hood. If you profile on iOS 9.3 it works fine.

Before `Constraints` where leaking where as now it's internal Swift data structures. There's not much I can do to fix those unfortunately.

**Comment by swiftli** [comment] 2016-09-20 06:44
@robertjpayne Thanks!

**Comment by Panajev** [comment] 2016-09-20 06:59
Could you make a radar in Apple's bug reporter and maybe post as well in either the dev forums or the swift mailing lists? This could be addressed before they ship Swift 3.1 hopefully.

**Comment by frogcjn** [comment] 2016-10-26 16:44
<img width="508" alt="2016-10-26 22 46 00" src="https://cloud.githubusercontent.com/assets/1777562/19735487/5e5ba3cc-9bde-11e6-8b4f-d95a27a8372e.png">
3.0.2 still have leaks. If this is the Leak Agent bug, then we should find the right way to reappear this issue.
