### ISSUE TITLE
SnapKit 0.10.0 crash on iOS7 in release on device

### ISSUE THREAD

**Issue by onix-nezhyborets** [SnapKit/SnapKit#81] opened 2015-04-18 11:46 UTC
Hi guys. I have updated my SnapKit submodule so it points now to  d44a9bebd2a4cc324fb100d5f9b089ee82b98521. It's all working fine (had to update code a little bit), but only on iOS7, only in release configuration and only when running on device (not on simulator) it crashes right away. Here is a screen shot of what we have in Fabric https://www.dropbox.com/s/nkecb8lgoh1sfmi/Screenshot%202015-04-18%2014.43.07.png?dl=0

and here is the code that calls it

![screenshot 2015-04-18 14 44 25](https://cloud.githubusercontent.com/assets/2803931/7215292/74b7b1c2-e5d9-11e4-9ad4-1d106bab1f25.png)

but even when i remove that part it crashes on some another one. 

Could you please give me and advice on this?

**Comment by robertjpayne** [comment] 2015-04-18 11:53
@onix-nezhyborets was this working before pointing towards SnapKit? Just trying to understand if it's a new issue or old issue etc…

From looks though – it may not be valid to add constraints that need to install on the view itself inside the view's constructor.

Just for sanity sake can you try overrideing the `updateConstraints` method and adding the constraints there? Make sure you use `snp_remakeConstraints` instead so it won't double up any.

I'm unfamiliar with the crash log you have there but the crash also looks to happen inside of UIKit not in SnapKit specifically.

**Comment by onix-nezhyborets** [comment] 2015-04-18 12:09
This is a very old code that worked on all version starting from Snappy. And as i said, it works on all simulators, on iOS8 device in both debug/release, and on iOS7 device in debug, but not in release. For me it doesn't seem to be a problem with my or SnapKit code, but maybe some target dependency or linking problem. But my suggestion is not fitting into situation either because it does call the SnapKit. 

I'll try remakeConstraints and will let you know if it works

**Comment by robertjpayne** [comment] 2015-04-18 12:17
@onix-nezhyborets so this same code was working fine with Snap/Snappy and Swift 1.2? Or did you do the Swift 1.2 upgrade in the process?

Remember that iOS 7.0 doesn't support embedded frameworks too so I hope you're directly including the source via a submodule?

Sounds like the Swift optimizer is doing something that iOS 7.0 doesn't like, but it's still weird.

**Comment by robertjpayne** [comment] 2015-04-19 10:14
@onix-nezhyborets How'd you go with remakeConstraints?

**Comment by onix-nezhyborets** [comment] 2015-04-20 10:23
Remake constraints didn't work, but we found out that it's not a iOS7 issue but 64-bit processors issue. Crashes an any iOS but only on not 64-bit processors (iphone 4s, iphone 5 5c, ipod 5, ipad 3 etc.).

**Comment by robertjpayne** [comment] 2015-04-20 10:26
@onix-nezhyborets and how are you integrating the library code if you don't mind me asking?

**Comment by onix-nezhyborets** [comment] 2015-04-20 10:32
by a submodule
![2015-04-20 13 31 26](https://cloud.githubusercontent.com/assets/2803931/7228435/bb397336-e761-11e4-99f1-fc1a57c2d2ee.png)
![2015-04-20 13 32 16](https://cloud.githubusercontent.com/assets/2803931/7228436/bb603c46-e761-11e4-9dcd-8398cfa8d003.png)

**Comment by robertjpayne** [comment] 2015-04-20 11:04
@onix-nezhyborets I wonder if it'd make any difference if you copy the SnapKit source into your project rather than using a framework.

I'm using SnapKit in an iOS 7.0 projects but without a framework and have no issues so it's odd that it's causing you issues only on 32-bit iOS 7.0.

**Comment by onix-nezhyborets** [comment] 2015-04-20 13:03
So what i found is that 0126a0efc2dcf144d0b134e15e7e241bef26018c (Fix up formatting) is working but next commit b014ab638a88b9ba8656e590fd96e5f898f2b101 (Finalise classes) is not.

**Comment by onix-nezhyborets** [comment] 2015-04-20 13:15
Trying to use source code instead of framework now

**Comment by onix-nezhyborets** [comment] 2015-04-20 13:44
Also tried to do remakeConstraints everywhere instead makeConstraints and it didn't help

**Comment by robertjpayne** [comment] 2015-04-20 13:52
@onix-nezhyborets can you share the project? even if privately? It's hard to do much else than give you some suggestions as I can't reproduce this. It's probably a unique set of circumstances.

I still am hesitant to say it's inside SnapKit itself as the crash log is happening after the constraints are made and inside of UIKit.

You can email through anything to robertpayne@me.com

**Comment by robertjpayne** [comment] 2015-04-22 12:32
@onix-nezhyborets can you try out develop branch? I removed all the final declarations as someone else is having a very strange issue related to them too. I still cannot reproduce on my end.

**Comment by robertjpayne** [comment] 2015-04-24 10:16
@onix-nezhyborets pretty sure this will fix your issues, seems to have fixed #84 as well which was oddly similar.

**Comment by robertjpayne** [comment] 2015-04-26 10:09
Closing this as SnapKit 0.11.0 is out and pretty sure it will fix this.

**Closed by robertjpayne** 2015-04-26 10:09 UTC
Labels: need info

**Comment by onix-nezhyborets** [comment] 2015-04-26 19:28
Thank you very much, i'll try when i have a chance
