### ISSUE TITLE
XCode 9.0 - SafeAreaLayoutGuides support

### ISSUE THREAD

**Issue by hitendradeveloper** [SnapKit/SnapKit#451] opened 2017-09-15 13:07 UTC
### New Issue Checklist

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | e.g. ios
 Platform Version        | e.g. 11.0
 SnapKit Version         | e.g. 3.2.0
 Integration Method      | e.g.cocoapods
 

### Issue Description

How to add bottom | top constraint with respect to SafeAreaLayoutGuides?
New changes in the XCode 9.0 GM version.
![screen shot 2017-09-15 at 6 33 22 pm](https://user-images.githubusercontent.com/9197369/30483520-ccac033e-9a44-11e7-81e7-b77d1318867d.png)

**Comment by jaredegan** [comment] 2017-09-15 15:24
From this issue, it seems like this is already possible: https://github.com/SnapKit/SnapKit/issues/448

Since `safeAreaLayoutGuide` is a `UILayoutGuide` instance.

**Comment by robertjpayne** [comment] 2017-09-17 02:43
Dupe of #448

**Closed by robertjpayne** 2017-09-17 02:43 UTC
