### ISSUE TITLE
Carthage build fails for SnapKit 3.1.0: no member 'owningView'

### ISSUE THREAD

**Issue by nezhyborets** [SnapKit/SnapKit#351] opened 2016-10-09 20:30 UTC
* [+] I have looked at the [Documentation](http://snapkit.io/docs)
* [+] I have read the [F.A.Q.](http://snapkit.io/faq)
* [+] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 8.0+
 SnapKit Version         | 3.1.0
 Integration Method      | carthage
 

### Issue Description

Carthage fails build with following output:

> The following build commands failed:
> 	CompileSwift normal x86_64
> 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
> (2 failures)
> /Users/oleksiinezhyborets/Projects/Debts/App/Carthage/Checkouts/SnapKit/Source/LayoutConstraintItem.swift:55:20: error: value of type 'ConstraintLayoutGuide' has no member 'owningView'
> A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/oleksiinezhyborets/Projects/Debts/App/Carthage/Checkouts/SnapKit/SnapKit.xcworkspace -scheme SnapKit -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	CompileSwift normal x86_64
> 	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
> (2 failures)

**Comment by robertjpayne** [comment] 2016-10-10 05:34
Dupe of #348

**Closed by robertjpayne** 2016-10-10 05:34 UTC
