### ISSUE TITLE
Swift language leaks memory when having constant on constraints.

### ISSUE THREAD

**Issue by soapsign** [SnapKit/SnapKit#225] opened 2016-04-19 02:48 UTC
### New Issue Checklist

* [X] I have looked at the [Documentation](http://snapkit.io/docs)
* [X] I have read the [F.A.Q.](http://snapkit.io/faq)

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 9.0
 SnapKit Version         | 2.0
 Integration Method      | cocoapods
 

### Issue Description

```
class PrototypeViewController: UIViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        
        let v = UIView()
        view.addSubview(v)
        v.snp_makeConstraints { (make) in
            make.center.equalTo(view).inset(12)
        }
    }
    
}
```

The above lines of code will cause memory leak. You can examine the leak by using instrument leak tool.

**Comment by robertjpayne** [comment] 2016-04-26 03:41
@soapsign thanks for the report, I'll have a look later tonight.

**Comment by cherishloveyou** [comment] 2016-04-27 06:40
have the same problem, run instrument leak

**Comment by googlb** [comment] 2016-04-28 07:03
Memory leak. Me too

**Comment by robertjpayne** [comment] 2016-04-30 08:49
@googlb @cherishloveyou @soapsign can any of you post the instruments trace showing the leak? I see a leak but it's not from SnapKit, rather it appears to be from Swift itself.

**Comment by nickskull** [comment] 2016-05-03 14:40
I am having the same issue, here's what I could get from Instruments so far.

In the first `awakeFromNib` function, there's just the classic `snp_makeConstraints()` call with some setup. I am using [weak self] inside the closure, but to no help :( 

![screen shot 2016-05-03 at 16 16 13](https://cloud.githubusercontent.com/assets/1776969/14986817/ac64cb46-114d-11e6-834a-4c05c69da1bd.png)

**Comment by robertjpayne** [comment] 2016-05-03 23:54
@nickskull do you have the full instrument screenshot on that? It doesn't reveal much about what is leaking vs what's an allocation/call stack.

Also does it happen in `viewDidLoad` apposed to `awakeFromNib`? I've only tested the `viewDidLoad` as this is what the issue request was opened with.

**Comment by nickskull** [comment] 2016-05-04 11:42
@robertjpayne What exactly should I take a screenshot of? AFAIK There wasn't really anything relevant in allocations. When looking into code, Instruments show all these `if let` and `else if let` as leaking in this code - https://github.com/SnapKit/SnapKit/blob/develop/Source/Constraint.swift#L388 .

**Comment by robertjpayne** [comment] 2016-05-04 12:33
@nickskull it looks like you've screenshotted the `Details > Call Tree` viewer. It'd be useful to also see what the `Details > Leaks > Leaks By Backtrace` look like.

As far as I can tell from your screenshot the leaks are occurring but not because of SnapKit but rather lower level libraries. `swift_slowAlloc` is a bit notorious on my radar for leaking lots and has nothing to do with SnapKit in reality.

**Comment by robertjpayne** [comment] 2016-05-04 12:38
Digging a bit deeper it looks entirely related around `snp_constantForValue`  but reviewing my code I'm not really doing anything here it's all value types in that method and from the rest of the backtrace sounds like the Swift runtime/compiler is allocing memory it isn't then cleaning up.

**Comment by nickskull** [comment] 2016-05-04 13:12
@robertjpayne Oh, I forgot to mention that - I don't think it's (*entirely*) SnapKit's fault, rather a Swift issue, but there usually is a workaround that makes the leaks go away. :D 

Screenshot attached, I didn't attach it before, because there's IMO no value/clue in it.
  
![screen shot 2016-05-04 at 15 11 41](https://cloud.githubusercontent.com/assets/1776969/15015169/8a7cc91c-120a-11e6-94fa-ea0744e07c5c.png)

**Comment by soapsign** [comment] 2016-05-04 14:25
Just a guess. Will it be related to `snp_constantForValue` is taking `Any?` as its parameter?

**Comment by nickskull** [comment] 2016-05-04 14:32
@soapsign I tried switching to `Any` in case optionals affected it, but that didn't help. And since it can be ints, floats, even structs like `UIEdgeInsets` there isn't really any other option than to use `Any`.

**Comment by robertjpayne** [comment] 2016-05-04 16:18
Yea I'm not really sure how far to dig on fixing this, it's probably something we're going to have to wait until Swift 3.0 or something.

**Comment by robertjpayne** [comment] 2016-05-04 16:19
I've renamed the issue, I don't want people to get scared that SnapKit is a memory sieve but I also don't want to close this. I'm happy to merge any PR's that resolve this I just personally don't have enough time at the moment to try and work around Swift in this instance.

**Comment by nickskull** [comment] 2016-05-04 16:54
@robertjpayne Thanks for the info. I will also have a look at SnapKit 0.30.0 (if it can be compiled and run) and see if the issue is occurring there.

**Comment by robertjpayne** [comment] 2016-05-06 07:35
At the moment I think 0.30.0 is close but not quite ready to replace 0.20.0, I need to find a spare weekend to finish it up 👍

**Comment by molezzz** [comment] 2016-05-07 07:37
Memory leak. Me too. When call ".inset()"

**Comment by nickskull** [comment] 2016-05-11 10:15
@robertjpayne Just verified that 0.30.0 fixes the leak as far as I can see. Tested in multiple places and no leaks occurred anymore.

**Comment by robertjpayne** [comment] 2016-05-11 10:16
@nickskull interesting, I'll see what I'm doing differently in 0.30.0 to get the constant values and see if I can backport it.

Saw your comment about a checklist, honestly I need to evaluate the codebase again to confirm what's left!

**Comment by nickskull** [comment] 2016-05-11 11:35
@robertjpayne I think it can have something to do with the `Any?` being passed as parameter as opposed to it being a instance variable in version 0.30.0 (haven't checked source of 0.30.0 that much though).  [Related code here.](https://github.com/SnapKit/SnapKit/blob/develop/Source/Constraint.swift#L386)

**Comment by robertjpayne** [comment] 2016-05-19 05:42
I just pushed 0.30.0.beta1 to Cocoapods, it actually should be quite stable though do expect a bug here or there potentially and the API has changed a bit.

**Comment by soapsign** [comment] 2016-05-30 08:28
Recently, come across similar type of leak again on my project. And I found that its pretty much related to a [Swift Bug](https://bugs.swift.org/browse/SR-1205?jql=text%20~%20%22casting%20leak%22) related to casting protocol argument to concrete type in function. So I guess the cause of those leaks will be these [casting](https://github.com/SnapKit/SnapKit/blob/develop/Source/Constraint.swift#L388)

**Comment by robertjpayne** [comment] 2016-09-01 13:46
Does anyone know if this is resolved in Swift 2.3? I know it's fixed in Swift 3.0…

**Comment by robertjpayne** [comment] 2016-09-14 10:07
Closing this as it's invalid now I believe, with the advent of Swift 2.3/3.0 we should see this pretty much fade away in due time.

**Closed by robertjpayne** 2016-09-14 10:07 UTC
Labels: help wanted, need info

**Comment by Tbwas** [comment] 2016-11-09 03:32
I am having the same issue at Swift 3.0
![image](https://cloud.githubusercontent.com/assets/10513969/20126436/28deffa4-a670-11e6-9b49-7e29708f985c.png)

**Comment by teamdisc** [comment] 2017-01-18 21:03
teamdkjl

**Comment by Adrift001** [comment] 2017-07-31 06:46
I am also having the same issue at Swift3.1.
