### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by romk1n** [SnapKit/SnapKit#438] opened 2017-08-04 18:31 UTC
### New Issue Checklist

🚫 If this template is not filled out your issue **will** be closed with no comment. 🚫

* [x] I have looked at the [Documentation](http://snapkit.io/docs)
* [x] I have read the [F.A.Q.](http://snapkit.io/faq)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |ios
 Platform Version        | 10.3.3
 SnapKit Version         | 3.2.0
 Integration Method      | cocoapods
 

### Issue Description

looks like snap kit is leaking memory has anyone seen it yet ?

```bash
      0 libsystem_malloc.dylib malloc_zone_calloc
   1 libsystem_malloc.dylib calloc
   2 libobjc.A.dylib realizeClass(objc_class*)
   3 libobjc.A.dylib objc_readClassPair
   4 libswiftCore.dylib swift_initClassMetadata_UniversalStrategy
   5 libswiftCore.dylib 0x10b165080
   6 libswiftCore.dylib swift_getGenericMetadata
   7 libswiftCore.dylib type metadata accessor for _ContiguousArrayStorage
   8 SnapKit type metadata accessor for _ContiguousArrayStorage<LayoutConstraint> /Users/roman/work/sneakers/sneakers-workflow-mobile/Pods/SnapKit/Source/Constraint.swift:0
   9 SnapKit specialized specialized _ContiguousArrayBuffer.init(_uninitializedCount : Int, minimumCapacity : Int) -> _ContiguousArrayBuffer<A> /Users/roman/work/sneakers/sneakers-workflow-mobile/Pods/SnapKit/Source/Constraint.swift:0
  10 SnapKit specialized Array._copyToNewBuffer(oldCount : Int) -> () /Users/roman/work/sneakers/sneakers-workflow-mobile/Pods/SnapKit/Source/Constraint.swift:0
  11 SnapKit specialized Constraint.init(from : ConstraintItem, to : ConstraintItem, relation : ConstraintRelation, sourceLocation : (String, UInt), label : String?, multiplier : ConstraintMultiplierTarget, constant : ConstraintConstantTarget, priority : ConstraintPriorityTarget) -> Constraint /Users/roman/work/sneakers/sneakers-workflow-mobile/Pods/SnapKit/Source/Constraint.swift:0
  12 SnapKit Constraint.init(from : ConstraintItem, to : ConstraintItem, relation : ConstraintRelation, sourceLocation : (String, UInt), label : String?, multiplier : ConstraintMultiplierTarget, constant : ConstraintConstantTarget, priority : ConstraintPriorityTarget) -> Constraint /Users/roman/work/sneakers/sneakers-workflow-mobile/Pods/SnapKit/Source/Constraint.swift:0
  13 SnapKit specialized static ConstraintMaker.makeConstraints(item : LayoutConstraintItem, closure : (ConstraintMaker) -> ()) -> () /Users/roman/work/sneakers/sneakers-workflow-mobile/Pods/SnapKit/Source/ConstraintMaker.swift:0
  14 SnapKit static ConstraintMaker.makeConstraints(item : LayoutConstraintItem, closure : (ConstraintMaker) -> ()) -> () /Users/roman/work/sneakers/sneakers-workflow-mobile/Pods/SnapKit/Source/ConstraintViewDSL.swift:0
  15 SnapKit ConstraintViewDSL.makeConstraints((ConstraintMaker) -> ()) -> () /Users/roman/work/sneakers/sneakers-workflow-mobile/Pods/SnapKit/Source/ConstraintViewDSL.swift:39

```

**Comment by robertjpayne** [comment] 2017-08-08 07:04
This is just Instruments incorrectly reporting memory leaks for weak refs. It's actually a bug that Xcode 9 and sorts fixes! Duplicate of #310

**Closed by robertjpayne** 2017-08-08 07:04 UTC
