### ISSUE TITLE
No such Module

### ISSUE THREAD

**Issue by reejosamuel** [SnapKit/SnapKit#82] opened 2015-04-20 10:48 UTC
Cocoapod version `0.37.0.beta.1`
I had the 0.36.4 before i updated to this beta version, i got the same error.

Im not getting an error with other libraries which is why decided to post it here instead of cocoapods issues.

Podfile
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SnapKit'  , '~> 0.10.0'
```

Terminal
```
⇒ pod install
Analyzing dependencies
Downloading dependencies
Installing SnapKit (0.10.0)
Generating Pods project
Integrating client project
```

Error in Project
![snapkit-error](https://cloud.githubusercontent.com/assets/1253679/7228619/039171d8-e76c-11e4-94c4-05ef72485d26.png)

Please suggest a way to resolve it, there is something i need to change?

**Comment by robertjpayne** [comment] 2015-04-20 10:51
Can you post a sample project to dropbox or similar? Hard to tell just from the missing module message…

**Comment by reejosamuel** [comment] 2015-04-20 11:20
@robertjpayne my bad. You can use the link to download a sample app i set up and got the same error.
https://www.dropbox.com/s/aihncbry2fllirv/error-snapkit.zip?dl=0

**Comment by robertjpayne** [comment] 2015-04-20 12:15
@reejosamuel I just re-ran pod install with `0.36.4` in the sample app you gave me and it compiles fine now.

Maybe just try to downgrade your cocoapods and re-run `pod install`?

**Comment by robertjpayne** [comment] 2015-04-22 12:29
@reejosamuel have you had any further developments on this? Otherwise I'm going to close this as not a bug.

**Comment by reejosamuel** [comment] 2015-04-22 12:30
Ok sure. The issue was solved after I followed your steps. Thanks

**Comment by robertjpayne** [comment] 2015-04-22 12:32
@reejosamuel glad to hear!

**Closed by robertjpayne** 2015-04-22 12:32 UTC
Labels: need info

**Comment by jonyMIND** [comment] 2018-05-28 12:16
Hi I am facing this issue with Xcode 9.3 Can you please let me know what is the solution for this.
