### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by ham1955burger** [SnapKit/SnapKit#329] opened 2016-09-21 16:21 UTC
using Swift 3.0 and SnapKit 3.0.1

2 errors

* Header 'SnapKit-Swift.h' not found
* Could not build Objective-C module 'SnapKit'

---
/* module.modulemap */

framework module SnapKit {
umbrella header "SnapKit-umbrella.h"

export *
module * { export * }
}

module SnapKit.Swift {
header "**SnapKit-Swift.h**"
}

---

how fix it?

**Comment by Chris-Corea** [comment] 2016-09-21 18:11
@ham1955burger ,

I saw this issue in my own project when Xcode would fail to build a pod. I don't believe this is an issue with SnapKit in particular, but is more likely caused by a missing project setting or more severe compilation error elsewhere in your project. 

Can you verify that your cocoapods version is at least 1.1.0.rc.2 and that you've updated to Xcode 8? 

I would also suggest taking a look at issue: #300; try to follow the steps to resolve that issue and see if it works out for you.

**Comment by robertjpayne** [comment] 2016-09-22 10:23
Closing because issue does not contain completed [Issue Template](https://github.com/SnapKit/SnapKit/blob/develop/ISSUE_TEMPLATE.md).

**Closed by robertjpayne** 2016-09-22 10:23 UTC
