### ISSUE TITLE
Xcode12.5 module compiled with Swift 5.3.2 cannot be imported by the Swift 5.4 compiler

### ISSUE THREAD

**Issue by WGFcode** [SnapKit/SnapKit#719] opened 2021-05-17 02:14 UTC
module compiled with Swift 5.3.2 cannot be imported by the Swift 5.4 compiler: /Users/XXX/Library/Developer/Xcode/DerivedData/NXY-bdiioyaaxczbxlgusvqtvlkagrqv/Build/Products/Debug-iphoneos/SnapKit.framework/Modules/SnapKit.swiftmodule/arm64-apple-ios.swiftmodule

**Comment by qyhongfan** [comment] 2021-06-08 02:21
same problem

**Comment by corbin-miller** [comment] 2021-06-08 05:40
So it still doesn't compile after 22 days?

**Comment by cguess** [comment] 2021-09-14 20:15
I believe this is the solution to the problem (if it's the same I've been having) https://developer.apple.com/forums/thread/658129.

**Comment by robertjpayne** [comment] 2021-09-15 04:20
Duplicate of #708

**Closed** 2021-09-15 04:32 UTC
Labels: need info
