### ISSUE TITLE
TopLayoutGuide constraints is not applied when UIView constructed with InterfaceBuilder

### ISSUE THREAD

**Issue by confile** [SnapKit/SnapKit#101] opened 2015-05-28 23:44 UTC
I created a UIViewController with a xib file. Here is my .xib content: 

![page1viewcontroller_xib](https://cloud.githubusercontent.com/assets/64265/7873543/e3b794ae-05a3-11e5-98aa-07de2456621c.png)

Here is the controller code: 
```
import UIKit

@objc(Page1ViewController)
class Page1ViewController: UIViewController {
  
  
  @IBOutlet weak var view2: UIView!
  
  
  override func viewDidLoad() {
    super.viewDidLoad()
    
    let view1 = UIView(frame: CGRectMake(50, 50, 100, 200))
    view1.backgroundColor = UIColor.greenColor()
    self.view.addSubview(view1)
    
    
    view1.snp_makeConstraints { (make) -> Void in
      make.top.equalTo(self.topGuide.snp_bottom)
      make.left.equalTo(self.view.snp_left)
      make.size.equalTo(100)
    }
    
  }
 
  
  override func viewWillAppear(animated: Bool) {
    view2.snp_makeConstraints { (make) -> Void in
      make.top.equalTo(self.topGuide.snp_bottom)
      make.left.equalTo(self.view.snp_left).offset(100)
      make.size.equalTo(100)
      
    }
  }
  
  
}




// For SnapKit
extension UIViewController {
  var bottomGuide: UIView {
    return self.bottomLayoutGuide as! UIView
  }
  
  var topGuide: UIView {
    return self.topLayoutGuide as! UIView
  }
}
```

When I run the app you see the following: 

![ios_simulator_-_iphone_6_-_iphone_6___ios_8_4__12h4098c_](https://cloud.githubusercontent.com/assets/64265/7873560/1dd2af5c-05a4-11e5-84cf-61ad5f5b86ca.png)

The green view which has been created in code works perfect with the bottom of the topLayoutGuide but the blue view which has been created with interface builder does not work correct.

**Comment by confile** [comment] 2015-05-28 23:47
I also get the following console output: 

```
2015-05-29 01:47:36.033 DeviceImagesTest[28874:753663] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSIBPrototypingLayoutConstraint:0x7f8a412c0a70 'IB auto generated at build time for view with fixed frame' V:|-(34)-[UIView:0x7f8a412be100]   (Names: '|':UIView:0x7f8a412bdff0 )>",
    "<_UILayoutSupportConstraint:0x7f8a412c2100 V:[_UILayoutGuide:0x7f8a412c1580(0)]>",
    "<_UILayoutSupportConstraint:0x7f8a412c20a0 V:|-(0)-[_UILayoutGuide:0x7f8a412c1580]   (Names: '|':UIView:0x7f8a412bdff0 )>",
    "<<DeviceImagesTest.LayoutConstraint:0x7f8a412e8740> <UIView:0x7f8a412e8eb0>.top == <_UILayoutGuide:0x7f8a412e9430>.bottom>"
)

Will attempt to recover by breaking constraint 
<<DeviceImagesTest.LayoutConstraint:0x7f8a412ea570> <UIView:0x7f8a412ea790>.top == <_UILayoutGuide:0x7f8a412ea660>.bottom>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-05-29 01:47:36.035 DeviceImagesTest[28874:753663] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSIBPrototypingLayoutConstraint:0x7f8a412c0560 'IB auto generated at build time for view with fixed frame' H:|-(404)-[UIView:0x7f8a412be100](LTR)   (Names: '|':UIView:0x7f8a412bdff0 )>",
    "<<DeviceImagesTest.LayoutConstraint:0x7f8a412e7ac0> <UIView:0x7f8a412e7b20>.left == <UIView:0x7f8a412e7b70>.left + 100.0>"
)

Will attempt to recover by breaking constraint 
<NSIBPrototypingLayoutConstraint:0x7f8a412c0560 'IB auto generated at build time for view with fixed frame' H:|-(404)-[UIView:0x7f8a412be100](LTR)   (Names: '|':UIView:0x7f8a412bdff0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-05-29 01:47:36.073 DeviceImagesTest[28874:753663] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSIBPrototypingLayoutConstraint:0x7f8a412c0ac0 'IB auto generated at build time for view with fixed frame' H:[UIView:0x7f8a412be100(163)]>",
    "<<DeviceImagesTest.LayoutConstraint:0x7f8a412e6f20> <UIView:0x7f8a412e6f40>.width == 100.0>"
)

Will attempt to recover by breaking constraint 
<NSIBPrototypingLayoutConstraint:0x7f8a412c0ac0 'IB auto generated at build time for view with fixed frame' H:[UIView:0x7f8a412be100(163)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-05-29 01:47:36.088 DeviceImagesTest[28874:753663] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSIBPrototypingLayoutConstraint:0x7f8a412c0b10 'IB auto generated at build time for view with fixed frame' V:[UIView:0x7f8a412be100(186)]>",
    "<<DeviceImagesTest.LayoutConstraint:0x7f8a412e7030> <UIView:0x7f8a412e7050>.height == 100.0>"
)

Will attempt to recover by breaking constraint 
<NSIBPrototypingLayoutConstraint:0x7f8a412c0b10 'IB auto generated at build time for view with fixed frame' V:[UIView:0x7f8a412be100(186)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-05-29 01:47:36.089 DeviceImagesTest[28874:753663] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSIBPrototypingLayoutConstraint:0x7f8a412c0a70 'IB auto generated at build time for view with fixed frame' V:|-(34)-[UIView:0x7f8a412be100]   (Names: '|':UIView:0x7f8a412bdff0 )>",
    "<_UILayoutSupportConstraint:0x7f8a412c2100 V:[_UILayoutGuide:0x7f8a412c1580(64)]>",
    "<_UILayoutSupportConstraint:0x7f8a412c20a0 V:|-(0)-[_UILayoutGuide:0x7f8a412c1580]   (Names: '|':UIView:0x7f8a412bdff0 )>",
    "<<DeviceImagesTest.LayoutConstraint:0x7f8a410556c0> <UIView:0x7f8a4104dd40>.top == <_UILayoutGuide:0x7f8a41014ab0>.bottom>"
)

Will attempt to recover by breaking constraint 
<<DeviceImagesTest.LayoutConstraint:0x7f8a410503c0> <UIView:0x7f8a4104cea0>.top == <_UILayoutGuide:0x7f8a4104c6a0>.bottom>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

**Comment by robertjpayne** [comment] 2015-05-29 00:36
@confile A few things:

1. We don't officially support interface builder, though it should be possible to mix and match we don't test against IB or try and patch any issues relating to IB only.

2. You are using `snp_makeConstraints` on `viewWillAppear` which is potentially going to result in lots of excess constraints over time (a new set will be installed every time viewWillAppear is invoked). You may want to use `snp_remakeConstraints` instead there.

3. The error output looks entirely related to IB and IB generated constraints or something I really have no idea I've never seen it.

Looking at your code and your screenshot it looks like it's installing the correct constraints and the visual output is intended. Is that not the case?

**Comment by confile** [comment] 2015-05-29 00:48
@robertjpayne The intension is that the green and the blue box are both equal and below the topLayout Guide.

**Comment by robertjpayne** [comment] 2015-05-29 00:49
@confile right so IB probably has installed some constraints that is affecting that, can you ensure all of IB's constraints are set to "placeholder"?

**Comment by confile** [comment] 2015-05-29 00:54
I did not install any constraint at all in the interface builder.

**Comment by robertjpayne** [comment] 2015-05-29 01:11
@confile any chance you can send your .xib or storyboard to robertpayne [at] me.com?

**Comment by confile** [comment] 2015-05-29 12:51
I solved it. You have to set ``remove at build time`` for each constraint. Then it works perfect. Thanks.

Is there a way that SnapKit can remove InterfaceBuilder constraints automatically?

**Comment by confile** [comment] 2015-05-29 13:58
@robertjpayne Here is the demo I made. Just run the code and you see the problem: 

https://github.com/confile/SnapKit-Test

**Comment by steffimueller** [comment] 2015-05-29 17:32
+1 @robertjpayne I have the same problem with views created in interface builder.

**Comment by robertjpayne** [comment] 2015-05-30 00:11
@steffimueller @confile the problem is interface builder constraints are not decipherable from regular constraints unless we try to do some potential fragile class matching magic. It's just a road I don't really want to take.

So I'm very happy to hear you've managed to fix it but I'm unsure we'll be able to provide any stable API that could handle removing IB's default constraints.

> In general I strongly recommend people do not use interface builder, Masonry/SnapKit were created to help increase productivity with 100% code based interfaces and now with lazy var's in Swift it's pretty quick to code up your interfaces. 

> It's a completely opinionated bias of my own but Interface Builder is a bad choice 99 out of 100 times for a variety of reasons. Most compelling to me is how poor they integrate with source control since they're nearly impossible to merge, how fiddly the tooling is trying to select elements, create constraints, copy n paste and last it's impossible to compose interfaces by embedding one xib in another.

**Closed** 2015-05-30 07:57 UTC
Labels: question

**Comment by confile** [comment] 2015-05-31 12:06
Thank you for help!

**Comment by confile** [comment] 2015-05-31 12:16
@robertjpayne Why do lazy var help to make interface generation being faster?

**Comment by robertjpayne** [comment] 2015-06-01 05:00
@confile compared to Objective-C it's easy now to declare a lot of your UI as lazy vars that are not initialised until you access them.

It just makes it easy to make code based UI's from a developers perspective not a performance perspective.

I suppose it's not much different than regular vars except you don't have to worry about nils and sorts.

**Comment by johndpope** [comment] 2016-09-19 14:32
I managed to get Snapkit to sit with / alongside IB.
https://gist.github.com/johndpope/46a4bb726a38d992d108eba5bb4ac0f2
